CREATE OR REPLACE TABLE public."POST" (
  post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT,
  visibility TEXT NOT NULL DEFAULT 'public' 
    CHECK (visibility IN ('public', 'friends', 'private')),
  status TEXT NOT NULL DEFAULT 'active' 
    CHECK (status IN ('active', 'hidden', 'deleted')),
  is_flagged BOOLEAN DEFAULT FALSE,
  ai_moderation_label TEXT, -- e.g. 'safe', 'haram', 'needs_review'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
