create table public."Share" (
  id bigint generated by default as identity not null,
  user_id uuid null,
  post_id bigint null,
  created_at timestamp with time zone not null default now(),
  constraint Share_pkey primary key (id),
  constraint Share_post_id_fkey foreign KEY (post_id) references "POST" (post_id),
  constraint Share_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;